### ISSUE TITLE
Disabling "edit" toolbar - PR proposal

### ISSUE THREAD

**Issue by chrisbolin** [alex3165/react-leaflet-draw#15]
I'd like to disable editing and just use the drawing features of Leaflet.Draw. In Leaflet.Draw this is done by setting the `edit` option to false (its default).

I'm totally happy to make a PR, just want to make sure you'd be amenable before I do anything. 

What I'd propose for a first effort is an optional `edit` prop. By default the behavior would be the same as it is now. When `edit` is explicitly set to `false` the `options` object (https://github.com/alex3165/react-leaflet-draw/blob/master/src/EditControl.js#L91) would be set to an empty object, without the `edit` sub-object.

What do you think? Just let me know and I can make a PR.

**Comment by alex3165** [comment]
Hey @chrisbolin it make sense, I would be happy to review and merge a PR from you for that.

**Comment by chrisbolin** [comment]
I chose to do this with CSS for my use-case. Easy enough! 

```css
.leaflet-draw-edit-edit { display: none !important; }
.leaflet-draw-edit-remove { display: none !important; }
```
